### ISSUE TITLE
should returns `errors`

### ISSUE THREAD

**Issue by griffin-stewie** [griffin-stewie/go-chatwork#5]
Currently go-chatwork does not have API call methods that returns `errors`, even if it gets error response like bellow.

```json
{"errors":["You don't have permission to send messages in this room"]}
```

I'm planning to implement that methods returns `errors`.

```go
func (c *Client) RoomMessage(roomID, messageID string) Message
// ↓
func (c *Client) RoomMessage(roomID, messageID string) Message, errors
```

**Comment by griffin-stewie** [comment]
@sue445 @yoppi @eiel

Any opinion?

**Comment by sue445** [comment]
@griffin-stewie I shink this is good :+1: 

This is breaking change, but I'm glad it is better to receive an error.

**Comment by griffin-stewie** [comment]
@sue445 thx!

**Comment by griffin-stewie** [comment]
marged
